# Generated by Django 4.1.5 on 2023-01-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="default_avatar.jpg", null=True, upload_to="avatar"
            ),
        ),
    ]
